---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ${K8S_USER}-binding
  namespace: ${K8S_NAMESPACE}
subjects:
- kind: User
  name: ${K8S_USER}
  apiGroup: ""
roleRef:
  kind: Role
  name: ${K8S_USER}
  apiGroup: ""
